Add range support
geniusproject/nefertari pull request #58
Opened 2016-10-31 20:26 UTC by nikitagromov

Pivotal story id [#](https://www.pivotaltracker.com/story/show/131987231)

2016-10-31 20:27 UTC, nikitagromov commented
Need to be merged after [this PR](https://github.com/geniusproject/nefertari/pull/57)

2016-11-02 17:38 UTC, nmenardg requested changes

2016-11-02 17:38 UTC, nmenardg commented on nefertari/es_query.py
> +    for index, token in enumerate(tokens):
`enumerate` is not necessary here

2016-11-02 17:38 UTC, nmenardg commented on nefertari/es_query.py
> +def _remove_needles_brackets(tokens):
_remove_needless_parentheses\*

2016-11-02 17:38 UTC, nmenardg commented on nefertari/es_query.py
> +            break
This is essentially what str.find() does:
https://docs.python.org/3.4/library/stdtypes.html#str.find

2016-11-02 17:38 UTC, nmenardg commented on tests/test_es_query.py
> +        assert ['item:value', 'OR', 'item:value'] == tree
Please follow our convention for equalities:
`actual == expected`
In this case, `tree` is actual, `['item:value', 'OR', 'item:value']` is expected

2016-11-02 17:38 UTC, nmenardg commented on tests/test_es_query.py
> +                 ['item:value', 'OR', 'item:value']]] == tree
`actual == expected`

2016-11-02 20:34 UTC, nmenardg approved these changes

2016-11-02 20:49 UTC, merged