Update tests
geniusproject/nefertari pull request #71
Opened 2016-12-06 23:31 UTC by nikitagromov

2016-12-06 23:38 UTC, nikitagromov commented
We need to change version of python to 3+ for CI

2016-12-07 14:50 UTC, nmenardg requested changes

2016-12-07 14:50 UTC, nmenardg commented on nefertari/elasticsearch.py
>              if isinstance(current_qs, str):
I think you should change this to
```python
if current_qs is not None:
```

2016-12-07 15:26 UTC, nmenardg approved these changes

2016-12-07 15:42 UTC, merged