Implement boost param
geniusproject/nefertari pull request #77
Opened 2017-03-13 08:58 UTC by nikitagromov

Pivotal story id [#139740111](https://www.pivotaltracker.com/story/show/139740111)

2017-03-13 20:07 UTC, nmenardg requested changes

2017-03-13 20:07 UTC, nmenardg commented on nefertari/es_query.py
> +        pass
Is this necessary?

2017-03-13 20:07 UTC, nmenardg commented on nefertari/es_query.py
> +    def append(buffer, tokens):
Why not use `@classmethod`?

2017-03-13 20:07 UTC, nmenardg commented on nefertari/es_query.py
> +        if value not in Tokenizer.query_keywords:
...and then `cls.query_keywords`

2017-03-13 20:07 UTC, nmenardg commented on nefertari/es_query.py
> +    def tokenize(query_string):
Same here

2017-03-13 20:07 UTC, nmenardg commented on nefertari/es_query.py
> +    def _remove_needless_parentheses(tokens):
Same here

2017-03-13 20:07 UTC, nmenardg commented on nefertari/es_query.py
> +        return self.cached
Why not use `self.value` and `self.cached` directly?

2017-03-13 20:07 UTC, nmenardg commented on nefertari/es_query.py
> +    def apply(self, term):
I think you could define those methods in the BaseProcessor as `@abstractmethod`

2017-03-13 20:10 UTC, nmenardg commented on nefertari/es_query.py
> +                return False
As Codacy highlighted, the `return False` could be directly in the function, after the `for`

2017-03-15 13:31 UTC, nmenardg approved these changes

2017-03-16 21:00 UTC, nmenardg requested changes

2017-03-16 21:00 UTC, nmenardg commented on tests/test_es_query.py
> +        #     'term': {'obj_status': 'active'}}]}}]}}
I think you forgot commented code here

2017-03-16 21:06 UTC, nikitagromov commented on tests/test_es_query.py
> +        #     'term': {'obj_status': 'active'}}]}}]}}
I left this here for readability

2017-03-16 21:10 UTC, nmenardg commented on tests/test_es_query.py
> +        #     'term': {'obj_status': 'active'}}]}}]}}
Please add a small explanation text

2017-03-17 12:43 UTC, nmenardg approved these changes

2017-03-23 15:39 UTC, merged