Split indexation into mupltiple processes
geniusproject/nefertari pull request #82
Opened 2017-05-10 14:20 UTC by nikitagromov

Pivotal story id [#143460457]https://www.pivotaltracker.com/story/show/143460457)

2017-05-10 18:37 UTC, nmenardg requested changes

2017-05-10 18:37 UTC, nmenardg commented on nefertari/scripts/es.py
> +                self._pool[process_id].append(ESTask(model_name, options))
Wouldn't it be simpler and more readable to reverse the `for` loop nesting and do something like this:
```python
self._pool = {}
for process_id in range(0, processes):
    self._pool[process_id] = []
    for model_name in model_names:
        self._pool[process_id].append(ESTask(model_name, options))
```

2017-05-10 18:37 UTC, nmenardg commented on nefertari/scripts/es.py
> +    def __call__(self):
If this is only called in `apply`, why not simply put the code in `apply`?

2017-05-10 22:13 UTC, nikitagromov commented on nefertari/scripts/es.py
> +    def __call__(self):
This is wrapper, because we can't pass object method as high order function to `map`

2017-05-11 13:36 UTC, nmenardg commented on nefertari/scripts/es.py
> +                    q.put((model_name, chunks[p]), block=False)
Do you do something with `model_chunks` afterwards? I don't quite understand what this method does

2017-05-11 13:39 UTC, nikitagromov commented on nefertari/scripts/es.py
> +                    q.put((model_name, chunks[p]), block=False)
I have queue which shared between processes. This method put model chunks to queue, and other processes take model chunks from queue.

2017-05-11 21:38 UTC, merged